# Generated by Django 2.1.3 on 2018-11-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20181121_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Read'), (2, 'Unread'), (3, 'Reading')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
