# Generated by Django 2.1.3 on 2018-11-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20181128_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='completion_date',
            field=models.DateField(null=True),
        ),
    ]
