# Generated by Django 2.1.3 on 2018-11-30 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20181130_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
