# Generated by Django 2.1.3 on 2018-11-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20181130_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='completion_date',
        ),
    ]
