# Generated by Django 2.1.3 on 2019-01-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_remove_book_completion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.PositiveSmallIntegerField(choices=[(21, 'Good'), (22, 'Fair'), (23, 'Bad')]),
        ),
    ]
