# Generated by Django 2.1.3 on 2019-01-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20190110_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Good'), (2, 'Fair'), (3, 'Bad')], default=1),
        ),
    ]
