# Generated by Django 2.1.3 on 2019-01-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_auto_20190114_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='review',
            field=models.PositiveSmallIntegerField(choices=[(4, 'Good'), (5, 'Fair'), (6, 'Bad')], default=4),
        ),
    ]
